postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: portfoliowebsite
    POSTGRES_PASSWORD: Sh!t1sS3cureS0n
  ports:
    - '5432:5432'
  volumes:
    - ~/.docker-volumes/portfoliowebsite/postgresql/data:/var/lib/postgresql/data

redis:
  image: redis:2.8.22
  ports:
    - '6379:6379'
  volumes:
    - ~/.docker-volumes/portfoliowebsite/redis/data:/var/lib/redis/data

portfoliowebsite:
  build: .
  command: gunicorn -b 0.0.0.0:8000 --reload --access-logfile - "portfoliowebsite.app:create_app()"
  environment:
    PYTHONUNBUFFERED: 'true'
  links:
    - postgres
    - redis
  volumes:
    - .:/portfoliowebsite
  ports:
    - '8000:8000'
